
"use strict";
if(!SocialNet.requireLogin())throw new Error("غير مسجل");
const feed=document.getElementById("feed"),body=document.getElementById("postBody"),img=document.getElementById("postImage"),pub=document.getElementById("publish");
async function load(){feed.innerHTML='<div class="card loading">جاري تحميل المنشورات...</div>';try{const d=await SocialNet.api("/api/posts");feed.innerHTML=d.posts.length?d.posts.map(render).join(""):'<div class="card empty">لا توجد منشورات بعد. كن أول من ينشر! ✨</div>'}catch(e){feed.innerHTML='<div class="card empty">'+SocialNet.escape(e.message)+'</div>'}}
function render(p){const comments=(p.comments||[]).map(c=>`<div class="comment"><strong>${SocialNet.escape(c.author)}</strong>${SocialNet.escape(c.body)}</div>`).join("");return `<article class="card post"><div class="post-head"><div class="author"><span class="avatar">👤</span><div><strong>${SocialNet.escape(p.author)}</strong><small>${SocialNet.date(p.created_at)}</small></div></div></div>${p.body?`<div class="post-body">${SocialNet.escape(p.body).replace(/\n/g,"<br>")}</div>`:""}${p.image_url?`<img class="post-image" src="${SocialNet.escapeAttr(p.image_url)}" onerror="this.style.display='none'" alt="صورة المنشور">`:""}<div class="post-tools"><button class="like ${p.liked?"liked":""}" data-like="${p.id}">❤️ ${p.likes_count||0}</button></div><div class="comments">${comments||'<span class="muted">لا توجد تعليقات بعد.</span>'}</div><form class="comment-form" data-comment="${p.id}"><input maxlength="500" placeholder="اكتب تعليقًا..." required><button class="btn btn-soft">إرسال</button></form></article>`}
feed.addEventListener("click",async e=>{const x=e.target.closest("[data-like]");if(!x)return;try{await SocialNet.api("/api/posts/"+x.dataset.like+"/like",{method:"POST"});load()}catch(err){alert(err.message)}});
feed.addEventListener("submit",async e=>{if(!e.target.matches("[data-comment]"))return;e.preventDefault();const id=e.target.dataset.comment,input=e.target.querySelector("input");try{await SocialNet.api("/api/posts/"+id+"/comments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:input.value.trim()})});input.value="";load()}catch(err){alert(err.message)}});
pub.addEventListener("click",async()=>{const b=body.value.trim(),u=img.value.trim();if(!b&&!u)return alert("اكتب نصًا أو ضع رابط صورة.");pub.disabled=true;try{await SocialNet.api("/api/posts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:b,imageUrl:u})});body.value="";img.value="";load()}catch(e){alert(e.message)}finally{pub.disabled=false}});
document.getElementById("refresh").addEventListener("click",load);document.getElementById("clearMine").addEventListener("click",async()=>{if(!confirm("هل تريد حذف جميع منشوراتك؟"))return;try{await SocialNet.api("/api/my-posts",{method:"DELETE"});load()}catch(e){alert(e.message)}});load();
