"use strict";
if(!SocialNet.requireLogin())throw new Error("غير مسجل");
const mf=document.getElementById("messageFile"),pl=document.getElementById("peopleList"),sl=document.getElementById("searchPeople"),ml=document.getElementById("messagesList"),head=document.getElementById("chatHead"),form=document.getElementById("messageForm"),input=document.getElementById("messageInput");let people=[],selected=null,poll=null,lastSignature="";
function drawPeople(){const q=sl.value.trim().toLowerCase();pl.innerHTML=people.filter(u=>u.name.toLowerCase().includes(q)).map(u=>`<button class="person ${selected&&selected.id==u.id?'selected':''}" data-user="${u.id}" data-name="${SocialNet.escapeAttr(u.name)}"><span class="avatar">👤</span>${SocialNet.escape(u.name)}</button>`).join('')||'<div class="empty">لا يوجد مستخدمون.</div>'}
function renderMessages(msgs){return msgs.length?msgs.map(m=>{const b=String(m.body||'');const content=b.startsWith('[SN_IMAGE]')?`<img class="image-message" src="${SocialNet.escapeAttr(b.slice(10))}" alt="صورة الرسالة">`:SocialNet.escape(b).replace(/\n/g,'<br>');return `<div class="bubble ${Number(m.sender_id)===Number(SocialNet.user()?.id)?'mine':'other'}">${content}<small>${SocialNet.date(m.created_at)}</small></div>`}).join(''):'<div class="empty">لا توجد رسائل بعد. ابدأ المحادثة الآن.</div>'}
async function openChat(id,name,quiet=false){selected={id:Number(id),name};drawPeople();head.textContent='💬 محادثة مع '+name;form.classList.remove('hidden');try{const d=await SocialNet.api('/api/messages/'+id);const sig=(d.messages||[]).map(m=>m.id+':'+m.body.length).join('|');if(sig!==lastSignature||!quiet){ml.innerHTML=renderMessages(d.messages||[]);ml.scrollTop=ml.scrollHeight;lastSignature=sig}}catch(e){if(!quiet)ml.innerHTML='<div class="empty">'+SocialNet.escape(e.message)+'</div>'}}
pl.addEventListener('click',e=>{const b=e.target.closest('[data-user]');if(b){lastSignature='';openChat(b.dataset.user,b.dataset.name)}});sl.addEventListener('input',drawPeople);
form.addEventListener('submit',async e=>{e.preventDefault();if(!selected||(!input.value.trim()&&!mf?.files[0]))return;const btn=form.querySelector('button');let text=input.value.trim();if(mf?.files[0]){try{text='[SN_IMAGE]'+await SocialMedia.fileToDataURL(mf.files[0],1200,.78)}catch(x){alert(x.message);return}}btn.disabled=true;try{await SocialNet.api('/api/messages/'+selected.id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:text})});input.value='';if(mf)mf.value='';lastSignature='';await openChat(selected.id,selected.name)}catch(x){alert(x.message)}finally{btn.disabled=false}});
(async()=>{try{people=(await SocialNet.api('/api/users')).users||[];drawPeople();const id=Number(new URLSearchParams(location.search).get('user'));const u=people.find(x=>Number(x.id)===id);if(u)openChat(u.id,u.name);poll=setInterval(()=>{if(selected)openChat(selected.id,selected.name,true)},2500)}catch(e){pl.innerHTML='<div class="empty">'+SocialNet.escape(e.message)+'</div>'}})();
