
"use strict";
if(!SocialNet.requireLogin())throw new Error("غير مسجل");
const pl=document.getElementById("peopleList"),sl=document.getElementById("searchPeople"),ml=document.getElementById("messagesList"),head=document.getElementById("chatHead"),form=document.getElementById("messageForm"),input=document.getElementById("messageInput");let people=[],selected=null;
function drawPeople(){const q=sl.value.trim().toLowerCase();pl.innerHTML=people.filter(u=>u.name.toLowerCase().includes(q)).map(u=>`<button class="person ${selected&&selected.id==u.id?"selected":""}" data-user="${u.id}" data-name="${SocialNet.escapeAttr(u.name)}">${SocialNet.avatarHTML(u.avatar_url,u.name)}<span>${SocialNet.escape(u.name)}</span></button>`).join("")||'<div class="empty">لا يوجد مستخدمون.</div>'}
async function openChat(id,name){selected={id:Number(id),name};drawPeople();head.textContent="💬 محادثة مع "+name;form.classList.remove("hidden");ml.innerHTML='<div class="loading">جاري تحميل الرسائل...</div>';try{const d=await SocialNet.api("/api/messages/"+id);ml.innerHTML=d.messages.length?d.messages.map(m=>{const sender=Number(m.sender_id)===Number(SocialNet.user()?.id)?SocialNet.user():people.find(x=>Number(x.id)===Number(m.sender_id));return `<div class="message-row ${Number(m.sender_id)===Number(SocialNet.user()?.id)?"mine":"other"}">${SocialNet.avatarHTML(sender?.avatar_url,sender?.name)}<div class="bubble">${SocialNet.escape(m.body).replace(/\n/g,"<br>")}<small>${SocialNet.date(m.created_at)}</small></div></div>`}).join(""):'<div class="empty">لا توجد رسائل بعد. ابدأ المحادثة الآن.</div>';ml.scrollTop=ml.scrollHeight}catch(e){ml.innerHTML='<div class="empty">'+SocialNet.escape(e.message)+'</div>'}}
pl.addEventListener("click",e=>{const b=e.target.closest("[data-user]");if(b)openChat(b.dataset.user,b.dataset.name)});sl.addEventListener("input",draw);
form.addEventListener("submit",async e=>{e.preventDefault();if(!selected||!input.value.trim())return;const btn=form.querySelector("button");btn.disabled=true;try{await SocialNet.api("/api/messages/"+selected.id,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:input.value.trim()})});input.value="";await openChat(selected.id,selected.name)}catch(x){alert(x.message)}finally{btn.disabled=false}});
(async()=>{try{people=(await SocialNet.api("/api/users")).users;drawPeople();const id=Number(new URLSearchParams(location.search).get("user"));const u=people.find(x=>Number(x.id)===id);if(u)openChat(u.id,u.name)}catch(e){pl.innerHTML='<div class="empty">'+SocialNet.escape(e.message)+'</div>'}})();
