"use strict";
if(!SocialNet.requireLogin())throw new Error("غير مسجل");
const fileInput=document.getElementById("profilePhoto"),preview=document.getElementById("photoPreview"),previewWrap=document.getElementById("photoPreviewWrap"),avatar=document.getElementById("profileAvatar");
let pending="";
function showAvatar(url){if(url){avatar.classList.add("has-image");avatar.innerHTML=`<img class="avatar-img" src="${SocialNet.escapeAttr(url)}" alt="الصورة الشخصية" onerror="this.remove();this.parentElement.classList.remove('has-image');this.parentElement.textContent='👤'">`}else{avatar.classList.remove("has-image");avatar.textContent="👤"}}
(async()=>{try{const [me,posts,users]=await Promise.all([SocialNet.me(),SocialNet.api("/api/posts"),SocialNet.api("/api/users")]);const u=me.user;sessionStorage.setItem("sn_user",JSON.stringify(u));document.getElementById("profileName").textContent=u.name;document.getElementById("profileId").textContent=u.id;document.getElementById("profileDate").textContent=SocialNet.date(u.created_at);document.getElementById("statPosts").textContent=(posts.posts||[]).filter(p=>Number(p.author_id)===Number(u.id)).length;document.getElementById("statUsers").textContent=(users.users||[]).length+1;showAvatar(u.avatar_url||localStorage.getItem("sn_avatar_"+u.id)||"")}catch(e){console.error(e)}})();
fileInput?.addEventListener("change",async()=>{const f=fileInput.files?.[0];if(!f)return;try{pending=await SocialMedia.fileToDataURL(f,800,.82);preview.src=pending;previewWrap.classList.remove("hidden")}catch(e){alert(e.message)}});
document.getElementById("saveProfilePhoto")?.addEventListener("click",async()=>{const u=SocialNet.user();if(!u||!pending)return alert("اختر صورة أولًا.");try{const d=await SocialNet.api("/api/me/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({avatarUrl:pending})});sessionStorage.setItem("sn_user",JSON.stringify(d.user));showAvatar(pending);pending="";fileInput.value="";previewWrap.classList.add("hidden");alert("تم حفظ الصورة الشخصية على الخادم.")}catch(e){alert(e.message)}});
document.getElementById("removeProfilePhoto")?.addEventListener("click",async()=>{const u=SocialNet.user();if(!u)return;try{await SocialNet.api("/api/me/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({avatarUrl:null})});localStorage.removeItem("sn_avatar_"+u.id);showAvatar("");pending="";fileInput.value="";previewWrap.classList.add("hidden")}catch(e){alert(e.message)}});
