"use strict";
require("dotenv").config();
const express=require("express");
const helmet=require("helmet");
const rateLimit=require("express-rate-limit");
const {Pool}=require("pg");
const crypto=require("crypto");
const path=require("path");

const app=express();
app.set("trust proxy",1);
app.use(helmet({contentSecurityPolicy:false}));
app.use(express.json({limit:"12mb"}));
app.use(rateLimit({windowMs:15*60*1000,max:600,standardHeaders:true,legacyHeaders:false}));

const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:false});
const SITE_PASSWORD=process.env.SITE_PASSWORD||"Boss2026";
const PORT=Number(process.env.PORT||3000);

async function q(text,params=[]){return pool.query(text,params)}
async function init(){
  await q(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL UNIQUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),avatar_url TEXT)`);
  await q(`ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT`);
  await q(`CREATE TABLE IF NOT EXISTS sessions(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS posts(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,body TEXT NOT NULL DEFAULT '',image_url TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS post_likes(id SERIAL PRIMARY KEY,post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,UNIQUE(post_id,user_id))`);
  await q(`CREATE TABLE IF NOT EXISTS comments(id SERIAL PRIMARY KEY,post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,body TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS messages(id SERIAL PRIMARY KEY,sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,receiver_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,body TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS friend_requests(id SERIAL PRIMARY KEY,sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,receiver_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(sender_id,receiver_id))`);
  await q(`CREATE TABLE IF NOT EXISTS friendships(id SERIAL PRIMARY KEY,user1_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,user2_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user1_id,user2_id),CHECK(user1_id<user2_id))`);
}
function hash(t){return crypto.createHash("sha256").update(t).digest("hex")}
async function auth(req,res,next){const h=req.get("authorization")||"";const token=h.startsWith("Bearer ")?h.slice(7):"";if(!token)return res.status(401).json({error:"يجب تسجيل الدخول."});const r=await q(`SELECT u.id,u.name,u.created_at,u.avatar_url FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1`,[hash(token)]);if(!r.rowCount)return res.status(401).json({error:"انتهت الجلسة. سجّل الدخول من جديد."});req.user=r.rows[0];next()}
function cleanName(v){return String(v||"").trim().replace(/\s+/g," ").slice(0,60)}
function cleanBody(v){return String(v||"").slice(0,12000)}

app.post("/api/enter",async(req,res)=>{try{if(String(req.body.password||"")!==SITE_PASSWORD)return res.status(403).json({error:"كلمة الدخول غير صحيحة."});const name=cleanName(req.body.name);if(name.length<2)return res.status(400).json({error:"اكتب اسمًا صحيحًا."});const r=await q(`INSERT INTO users(name) VALUES($1) ON CONFLICT(name) DO UPDATE SET name=EXCLUDED.name RETURNING id,name,created_at,avatar_url`,[name]);const token=crypto.randomBytes(32).toString("hex");await q(`INSERT INTO sessions(user_id,token_hash) VALUES($1,$2)`,[r.rows[0].id,hash(token)]);res.json({ok:true,token,user:r.rows[0]})}catch(e){console.error(e);res.status(500).json({error:"تعذر تسجيل الدخول."})}});
app.get("/api/me",auth,(req,res)=>res.json({user:req.user}));
app.post("/api/logout",auth,async(req,res)=>{const h=req.get("authorization")||"";const token=h.slice(7);await q(`DELETE FROM sessions WHERE token_hash=$1`,[hash(token)]);res.json({ok:true})});
app.get("/api/users",auth,async(req,res)=>{const r=await q(`SELECT id,name,created_at,avatar_url FROM users WHERE id<>$1 ORDER BY name`,[req.user.id]);res.json({users:r.rows})});
app.patch("/api/me/profile",auth,async(req,res)=>{const avatar=req.body.avatarUrl?String(req.body.avatarUrl):null;if(avatar&&avatar.length>4000000)return res.status(400).json({error:"الصورة كبيرة جدًا."});const r=await q(`UPDATE users SET avatar_url=$1 WHERE id=$2 RETURNING id,name,created_at,avatar_url`,[avatar,req.user.id]);res.json({user:r.rows[0]})});

app.get("/api/friends",auth,async(req,res)=>{const id=req.user.id;const friends=await q(`SELECT u.id,u.name,u.created_at,u.avatar_url FROM friendships f JOIN users u ON u.id=CASE WHEN f.user1_id=$1 THEN f.user2_id ELSE f.user1_id END WHERE f.user1_id=$1 OR f.user2_id=$1 ORDER BY u.name`,[id]);const incoming=await q(`SELECT fr.id,u.id AS user_id,u.name,u.created_at,u.avatar_url,fr.created_at AS requested_at FROM friend_requests fr JOIN users u ON u.id=fr.sender_id WHERE fr.receiver_id=$1 AND fr.status='pending' ORDER BY fr.created_at DESC`,[id]);const outgoing=await q(`SELECT fr.id,u.id AS user_id,u.name,u.created_at,u.avatar_url,fr.created_at AS requested_at FROM friend_requests fr JOIN users u ON u.id=fr.receiver_id WHERE fr.sender_id=$1 AND fr.status='pending' ORDER BY fr.created_at DESC`,[id]);res.json({friends:friends.rows,incoming:incoming.rows,outgoing:outgoing.rows})});
app.post("/api/friends/request/:userId",auth,async(req,res)=>{const target=Number(req.params.userId);if(!target||target===req.user.id)return res.status(400).json({error:"لا يمكنك إرسال طلب إلى نفسك."});const u=await q(`SELECT id FROM users WHERE id=$1`,[target]);if(!u.rowCount)return res.status(404).json({error:"المستخدم غير موجود."});const pair=await q(`SELECT id FROM friendships WHERE user1_id=LEAST($1,$2) AND user2_id=GREATEST($1,$2)`,[req.user.id,target]);if(pair.rowCount)return res.status(409).json({error:"أنتما صديقان بالفعل."});const old=await q(`SELECT id,sender_id,receiver_id,status FROM friend_requests WHERE ((sender_id=$1 AND receiver_id=$2) OR (sender_id=$2 AND receiver_id=$1)) AND status='pending' ORDER BY id DESC LIMIT 1`,[req.user.id,target]);if(old.rowCount){if(old.rows[0].sender_id===target){const a=await q(`UPDATE friend_requests SET status='accepted' WHERE id=$1 RETURNING *`,[old.rows[0].id]);await q(`INSERT INTO friendships(user1_id,user2_id) VALUES(LEAST($1,$2),GREATEST($1,$2)) ON CONFLICT DO NOTHING`,[req.user.id,target]);return res.json({ok:true,status:"accepted",request:a.rows[0]})}return res.status(409).json({error:"تم إرسال طلب الصداقة مسبقًا."})}const r=await q(`INSERT INTO friend_requests(sender_id,receiver_id) VALUES($1,$2) RETURNING id,sender_id,receiver_id,status,created_at`,[req.user.id,target]);res.json({ok:true,status:"pending",request:r.rows[0]})});
app.post("/api/friends/request/:requestId/accept",auth,async(req,res)=>{const rid=Number(req.params.requestId);const r=await q(`SELECT * FROM friend_requests WHERE id=$1 AND receiver_id=$2 AND status='pending'`,[rid,req.user.id]);if(!r.rowCount)return res.status(404).json({error:"طلب الصداقة غير موجود."});const x=r.rows[0];await q(`UPDATE friend_requests SET status='accepted' WHERE id=$1`,[rid]);await q(`INSERT INTO friendships(user1_id,user2_id) VALUES(LEAST($1,$2),GREATEST($1,$2)) ON CONFLICT DO NOTHING`,[x.sender_id,x.receiver_id]);res.json({ok:true})});
app.post("/api/friends/request/:requestId/reject",auth,async(req,res)=>{const rid=Number(req.params.requestId);const r=await q(`UPDATE friend_requests SET status='rejected' WHERE id=$1 AND receiver_id=$2 AND status='pending' RETURNING id`,[rid,req.user.id]);if(!r.rowCount)return res.status(404).json({error:"طلب الصداقة غير موجود."});res.json({ok:true})});
app.delete("/api/friends/:userId",auth,async(req,res)=>{const target=Number(req.params.userId);await q(`DELETE FROM friendships WHERE user1_id=LEAST($1,$2) AND user2_id=GREATEST($1,$2)`,[req.user.id,target]);res.json({ok:true})});

app.get("/api/messages/:userId",auth,async(req,res)=>{const other=Number(req.params.userId);if(!other)return res.status(400).json({error:"مستخدم غير صالح."});const u=await q(`SELECT id,name,created_at,avatar_url FROM users WHERE id=$1`,[other]);if(!u.rowCount)return res.status(404).json({error:"المستخدم غير موجود."});const m=await q(`SELECT m.id,m.sender_id,m.receiver_id,m.body,m.created_at,u.name AS sender FROM messages m JOIN users u ON u.id=m.sender_id WHERE (m.sender_id=$1 AND m.receiver_id=$2) OR (m.sender_id=$2 AND m.receiver_id=$1) ORDER BY m.created_at ASC LIMIT 500`,[req.user.id,other]);res.json({user:u.rows[0],messages:m.rows})});
app.post("/api/messages/:userId",auth,async(req,res)=>{const other=Number(req.params.userId),body=cleanBody(req.body.body);if(!other||other===req.user.id)return res.status(400).json({error:"مستلم غير صالح."});if(!body)return res.status(400).json({error:"الرسالة فارغة."});const u=await q(`SELECT id FROM users WHERE id=$1`,[other]);if(!u.rowCount)return res.status(404).json({error:"المستخدم غير موجود."});const r=await q(`INSERT INTO messages(sender_id,receiver_id,body) VALUES($1,$2,$3) RETURNING id,sender_id,receiver_id,body,created_at`,[req.user.id,other,body]);res.json({ok:true,message:r.rows[0]})});

app.get("/api/posts",auth,async(req,res)=>{const p=await q(`SELECT p.id,p.body,p.image_url,p.created_at,p.user_id AS author_id,u.name AS author,COUNT(DISTINCT l.id)::int AS likes_count,EXISTS(SELECT 1 FROM post_likes x WHERE x.post_id=p.id AND x.user_id=$1) AS liked FROM posts p JOIN users u ON u.id=p.user_id LEFT JOIN post_likes l ON l.post_id=p.id GROUP BY p.id,u.name ORDER BY p.created_at DESC LIMIT 100`,[req.user.id]);for(const x of p.rows){const c=await q(`SELECT c.id,c.post_id,c.body,c.created_at,u.name AS author FROM comments c JOIN users u ON u.id=c.user_id WHERE c.post_id=$1 ORDER BY c.created_at ASC`,[x.id]);x.comments=c.rows}res.json({posts:p.rows})});
app.post("/api/posts",auth,async(req,res)=>{const body=cleanBody(req.body.body),imageUrl=req.body.imageUrl?String(req.body.imageUrl):null;if(!body&&!imageUrl)return res.status(400).json({error:"المنشور فارغ."});if(imageUrl&&imageUrl.length>9000000)return res.status(400).json({error:"الصورة كبيرة جدًا."});const r=await q(`INSERT INTO posts(user_id,body,image_url) VALUES($1,$2,$3) RETURNING *`,[req.user.id,body,imageUrl]);res.json({ok:true,post:r.rows[0]})});
app.post("/api/posts/:id/like",auth,async(req,res)=>{const id=Number(req.params.id);const a=await q(`DELETE FROM post_likes WHERE post_id=$1 AND user_id=$2 RETURNING id`,[id,req.user.id]);if(!a.rowCount)await q(`INSERT INTO post_likes(post_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[id,req.user.id]);res.json({ok:true})});
app.post("/api/posts/:id/comments",auth,async(req,res)=>{const body=cleanBody(req.body.body).trim();if(!body)return res.status(400).json({error:"التعليق فارغ."});const r=await q(`INSERT INTO comments(post_id,user_id,body) VALUES($1,$2,$3) RETURNING id,post_id,body,created_at`,[Number(req.params.id),req.user.id,body]);res.json({ok:true,comment:r.rows[0]})});
app.delete("/api/my-posts",auth,async(req,res)=>{await q(`DELETE FROM posts WHERE user_id=$1`,[req.user.id]);res.json({ok:true})});

app.use(express.static(path.join(__dirname)));
app.get("*",(req,res)=>{if(req.path.startsWith("/api/"))return res.status(404).json({error:"المسار غير موجود."});res.sendFile(path.join(__dirname,"index.html"))});
init().then(()=>app.listen(PORT,()=>console.log(`SocialNet running on ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
